Repository mongodb/docs-php-library, pull requests merged in 2025-03, with the labels that each got.

#209 DOCSP-47864: sort order for updateone / replaceone
  source/reference/method/MongoDBCollection-bulkWrite.txt
  source/reference/method/MongoDBCollection-replaceOne.txt
  source/reference/method/MongoDBCollection-updateOne.txt
  source/whats-new.txt
  source/write/replace.txt
  source/write/update.txt
Labels: backport v1.21

#206 DOCSP-43464: operations with builders
  source/aggregation.txt
  source/builders.txt
  source/includes/builders.php
  source/index.txt
  source/read/change-streams.txt
  source/read/specify-a-query.txt
Labels: backport v1.21

#218 [PHP] Remove "MongoDB" from page title
  source/index.txt
  source/read.txt
Labels: backport v1.20, backport v1.21

#217 DOCSP-47217: pipeline param
  source/aggregation.txt
  source/aggregation/atlas-search.txt
  source/aggregation/vector-search.txt
  source/includes/aggregation/aggregation.php
  source/includes/aggregation/atlas-search.php
  source/includes/aggregation/vector-search.php
  source/read/cursor.txt
  source/reference/method/MongoDBCollection-aggregate.txt
  source/reference/method/MongoDBDatabase-aggregate.txt
  source/whats-new.txt
Labels: backport v2.0

#224 [PHP] Duplicate Titles - Connect to MongoDB
  snooty.toml
  source/get-started.txt
  source/get-started/create-a-connection-string.txt
  source/get-started/create-a-deployment.txt
  source/get-started/download-and-install.txt
  source/get-started/next-steps.txt
  source/get-started/run-sample-query.txt
  source/includes/get-started/troubleshoot.rst
Labels: backport v1.20, backport v1.21, backport v2.0
